version: "3.9"
services:
 
  couchdb:
    image: couchdb:3.2.0
    hostname: couchdb
    ports:
      - "5984:5984"
    volumes:
      - $HOME/.secrets/couchdb/local.ini:/opt/couchdb/etc/local.ini

  rabbitmq:
    image: rabbitmq:3.8.8-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.60.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver

  dockeragent:
    hostname: dockeragent
    build:
      context: .
      dockerfile: blogdeployments.dockeragent/Dockerfile
    environment:
      - Logging__LogLevel__blogdeployments=trace
      - RabbitMQ__HostName=rabbitmq
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "rabbitmq"

  agentsmith:
    hostname: agentsmith
    build:
      context: .
      dockerfile: blogdeployments.agent/Dockerfile
    environment:
      - Logging__LogLevel__blogdeployments=trace
#      - Agent__RunningInContainer=true
      - Agent__DryRun=false
      - RabbitMQ__HostName=rabbitmq
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 12350:80
    depends_on:
      - "rabbitmq"
      - "power"
      - "api"
  
  agentjohnson:
    hostname: agentjohnson
    build:
      context: .
      dockerfile: blogdeployments.agent/Dockerfile
    environment:
      - Logging__LogLevel__blogdeployments=trace
#      - Agent__RunningInContainer=true
      - Agent__DryRun=false
      - RabbitMQ__HostName=rabbitmq
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 12351:80
    depends_on:
      - "rabbitmq"
      - "power"
      - "api"

  power:
    hostname: power
    build: 
      context: .
      dockerfile: blogdeployments.power/Dockerfile
    environment:
      - Logging__LogLevel__blogdeployments=trace
      - RabbitMQ__HostName=rabbitmq
      - Raspbee__Proto=http
      - Raspbee__Host=192.168.1.123
      - Raspbee__Port=8080
      - Raspbee__LightId=0c:43:14:ff:fe:a3:b1:c2-01
      - couchdb__proto=http
      - couchdb__host=couchdb
      - couchdb__port=5984
      - couchdb__user=Administrator
      - couchdb__password=A8pi2shuYkeUjYfudKRtFsHCoP
      - ClusterTopology__ClusterId=852b1adc-9999-4db6-9b48-809f346b5fe3
      - ClusterTopology__Hosts__0=agentsmith
      - ClusterTopology__Hosts__1=agentjohnson
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8081:80
    depends_on:
      - "rabbitmq"
      - "couchdb"

  api:
    hostname: api
    build:
      context: .
      dockerfile: blogdeployments.api/Dockerfile
    environment:
      - Logging__LogLevel__blogdeployments=trace
      - RabbitMQ__HostName=rabbitmq
      - couchdb__proto=http
      - couchdb__host=couchdb
      - couchdb__port=5984
      - couchdb__user=Administrator
      - couchdb__password=A8pi2shuYkeUjYfudKRtFsHCoP
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
    depends_on:
      - "rabbitmq"
      - "couchdb"
