version: "3.9"
services:
  couchdb:
    image: couchdb:3.2.2
    hostname: couchdb
    ports:
      - "5984:5984"
    volumes:
      - $HOME/.secrets/couchdb/local.ini:/opt/couchdb/etc/local.ini

  rabbitmq:
    image: rabbitmq:3.8.8-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.60.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver