name: Docker Image CI

on:
  push:
    paths:
      - 'blogdeployments.dockeragent'
      - '.github/workflows/blogdeployments.dockeragent.yaml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file blogdeployments.dockeragent/Dockerfile --tag dockeragent:$(date +%s)
