on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: blogdeployments.power.ui
      - run: npm run build --if-present
        working-directory: blogdeployments.power.ui
#      - run: npm test
#        working-directory: blogdeployments.power.ui
      
#      - uses: azure/login@v1
#        name: Azure Login
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#      - run: |
#          az functionapp list --query "[?state=='Running']"
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: 'v10'
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: azcopy_v10 copy --source . --destination "https://powerpipelines.blob.core.windows.net/$web" --recursive --set-content-type
        working-directory: blogdeployments.power.ui/build
